name = "Transducers"
uuid = "b23992b4-06e5-11e9-2b42-995ad602865f"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["InteractiveUtils", "Statistics", "Test"]
