name = "Transducers"
uuid = "b23992b4-06e5-11e9-2b42-995ad602865f"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Dates", "Documenter", "InteractiveUtils", "Random", "Statistics", "Test"]
